function [x,fval]=LOC_Optimizer(objective,x0,maxIter)
% Run quasi-Newton optimization
% fminunc is preferred because analytic gradients are supplied
try
    options=optimoptions("fminunc",...
        "Algorithm","quasi-newton",...
        "SpecifyObjectiveGradient",true,...
        "Display","off",...
        "MaxIterations",maxIter,...
        "MaxFunctionEvaluations",maxIter*20);
    [x,fval]=fminunc(objective,x0,options);

catch optimizerError
    warning("LOC:OptimizerFallback",...
        "fminunc failed (%s).Using fminsearch without analytic gradients.",...
        optimizerError.message);
    scalarObjective=@(z)LOC_ScalarObjective(objective,z);
    options=optimset(...
        "Display","iter",...
        "MaxIter",maxIter,...
        "MaxFunEvals",maxIter*100);
    [x,fval]=fminsearch(scalarObjective,x0,options);
end
end